version: 2

sources:
  - name: raw
    schema: gz_ra_data
    description: greenweez raw data source
    tables:
      - name: sales
        identifier: raw_gz_sales
        description: sales of Greenweez / we have one row per productid found in each orders_id
        columns:
          - name: date_date
            description: the date of purchase
        tests:
          - dbt_utils.unique_combination_of_columns:
              combination_of_columns:
                - orders_id
                - pdt_id
      - name: product
        identifier: raw_gz_product
        description: products of greenweez
        columns:
          - name: products_id
            description: primary key of the table
            tests:
              - unique
              - not_null
      - name: ship
        identifier: raw_gz_ship
        description: ship of greenweez
        columns:
          - name: orders_id
            description: primary key of the table
            tests:
              - unique
              
models:
- name: int_sales_margin
  tests:
    - unique:
        column_name: "(orders_id || '-' || products_id)"
    - not_null:
        column_name:
          - orders_id
          - products_id
          - margin
          - Purchase_cost
          - date_date
          - revenue
          - quantity
